x = cat(3, magic(8), ones(8));


%% Shapes
assert(isequal( ...
    size(dct_2d(x)), ...
    size(x) ...
));
assert(isequal( ...
    size(idct_2d(x)), ...
    size(x) ...
));


%% Inverse transform is really the inverse
delta = idct_2d(dct_2d(x)) - x;
assert(all(delta < 1e-6, 'all'));
