Q = readmatrix('luminance_quantum.csv');
x = randi([-100 100], 8, 8, 12);


%% Shapes
assert(isequal( ...
    size(quantize(x, Q)), ...
    size(x) ...
));
assert(isequal( ...
    size(dequantize(quantize(x, Q), Q)), ...
    size(x) ...
));


%% Inverse
quantized = quantize(x, Q);
assert(isequal( ...
    size(quantize(dequantize(quantized, Q), Q)), ...
    size(quantized) ...
));
