rng(4);
x = randn(8, 8, 3);
y = randn(64, 4);


%% Permutations
assert(isequal( ...
    reshape(zigzag_permutation(3), 3, []), ...
    [ ...
        1 2 6; ...
        3 5 7; ...
        4 8 9; ...
    ] ...
));


%% Shapes
assert(isequal( ...
    size(zigzag_destruct(x)), ...
    [64 3] ...
));
assert(isequal( ...
    size(zigzag_construct(y)), ...
    [8 8 4] ...
));


%% Inverse
assert(isequal( ...
    zigzag_construct(zigzag_destruct(x)), ...
    x ...
));
assert(isequal( ...
    zigzag_destruct(zigzag_construct(y)), ...
    y ...
));
